/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/46A72tlnMJB
 */


export function Badges() {
  return (
    <div className="flex items-center space-x-4">
      <button
        className="rounded-md border border-gray-200 bg-white px-3 py-1 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-50 dark:bg-gray-900 dark:hover:bg-gray-50/80 dark:border-gray-800"
        type="button"
      >
        World War I
      </button>
      <button
        className="rounded-md border border-gray-200 bg-white px-3 py-1 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-50 dark:bg-gray-900 dark:hover:bg-gray-50/80 dark:border-gray-800"
        type="button"
      >
        Moon Landing
      </button>
      <button
        className="rounded-md border border-gray-200 bg-white px-3 py-1 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-50 dark:bg-gray-900 dark:hover:bg-gray-50/80 dark:border-gray-800"
        type="button"
      >
        Fall of the Berlin Wall
      </button>
      <button
        className="rounded-md border border-gray-200 bg-white px-3 py-1 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-50 dark:bg-gray-900 dark:hover:bg-gray-50/80 dark:border-gray-800"
        type="button"
      >
        Invention of the Internet
      </button>
    </div>
  )
}
