/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AVFL2M9zhNU
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { ResponsiveBar } from "@nivo/bar"
import { JSX, ClassAttributes, HTMLAttributes } from "react"

export function baGraph() {
  return (
    <div className="flex justify-center py-8">
      <div className="flex w-full max-w-6xl bg-white shadow-md">
        <div className="flex flex-col items-center w-1/2 p-4 border-r">
          <Select>
            <SelectTrigger id="category">
              <SelectValue placeholder="Others" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="option1">Option 1</SelectItem>
              <SelectItem value="option2">Option 2</SelectItem>
              <SelectItem value="option3">Option 3</SelectItem>
            </SelectContent>
          </Select>
          <img
            alt="Human Silhouette"
            className="my-4"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "200/300",
              objectFit: "cover",
            }}
            width="200"
          />
          <div className="grid grid-cols-2 gap-4">
            <Button className="bg-gray-200">100%</Button>
          </div>
        </div>
        <div className="w-1/2 p-4">
          <div className="text-center">
            <h2 className="text-xl font-bold">TOTAL DISABILITY RATING</h2>
            <BarChart className="w-[200px] h-[200px] mx-auto my-4" />
            <p className="text-lg">CALCULATED DISABILITY RATING OF 60%</p>
            <hr className="my-4" />
            <h2 className="text-xl font-bold">TOTAL MONTHLY COMPENSATION</h2>
            <p className="text-lg">$ 1361.88</p>
          </div>
        </div>
      </div>
    </div>
  )
}


function BarChart(props: JSX.IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}
