/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/93D6ftOxNYn
 */
import { TooltipTrigger, TooltipContent, Tooltip, TooltipProvider } from "@/components/ui/tooltip"

export function Body() {
  return (
    <section className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div className="flex flex-col items-center justify-center space-y-6">
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <div className="w-24 h-24 bg-gray-300 rounded-full cursor-pointer dark:bg-gray-700">
                <span className="sr-only">Head</span>
              </div>
            </TooltipTrigger>
            <TooltipContent>
              <p>Head</p>
            </TooltipContent>
          </Tooltip>
          <div className="flex items-center justify-between w-64">
            <Tooltip>
              <TooltipTrigger asChild>
                <div className="w-12 h-36 bg-gray-300 rounded-lg cursor-pointer dark:bg-gray-700">
                  <span className="sr-only">Left Arm</span>
                </div>
              </TooltipTrigger>
              <TooltipContent>
                <p>Left Arm</p>
              </TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger asChild>
                <div className="w-32 h-48 bg-gray-300 rounded-lg cursor-pointer dark:bg-gray-700">
                  <span className="sr-only">Torso</span>
                </div>
              </TooltipTrigger>
              <TooltipContent>
                <p>Torso</p>
              </TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger asChild>
                <div className="w-12 h-36 bg-gray-300 rounded-lg cursor-pointer dark:bg-gray-700">
                  <span className="sr-only">Right Arm</span>
                </div>
              </TooltipTrigger>
              <TooltipContent>
                <p>Right Arm</p>
              </TooltipContent>
            </Tooltip>
          </div>
          <div className="flex items-end justify-between w-32">
            <Tooltip>
              <TooltipTrigger asChild>
                <div className="w-12 h-32 bg-gray-300 rounded-lg cursor-pointer dark:bg-gray-700">
                  <span className="sr-only">Left Leg</span>
                </div>
              </TooltipTrigger>
              <TooltipContent>
                <p>Left Leg</p>
              </TooltipContent>
            </Tooltip>
            <Tooltip>
              <TooltipTrigger asChild>
                <div className="w-12 h-32 bg-gray-300 rounded-lg cursor-pointer dark:bg-gray-700">
                  <span className="sr-only">Right Leg</span>
                </div>
              </TooltipTrigger>
              <TooltipContent>
                <p>Right Leg</p>
              </TooltipContent>
            </Tooltip>
          </div>
        </TooltipProvider>
      </div>
    </section>
  )
}
